// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class ActorsWithMovieInfo
{
    public string Nconst { get; set; }

    public string Tconst { get; set; }

    public string ActorName { get; set; }

    public int? BirthYear { get; set; }

    public int? DeathYear { get; set; }

    public string PrimaryProfession { get; set; }

    public string Country { get; set; }
}