// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class MoviesWithActor
{
    public string Nconst { get; set; }

    public string Tconst { get; set; }

    public string MovieTitle { get; set; }

    public string Country { get; set; }

    public decimal? AverageRating { get; set; }

    public int? NumVotes { get; set; }

    public string TitleType { get; set; }

    public int? StartYear { get; set; }

    public int? RuntimeMinutes { get; set; }

    public string Genres { get; set; }
}